### ISSUE TITLE
Error when running command:

### ISSUE THREAD

**Issue by Raiders95** [nov1n/RemarkablePocket#12]
Hello,

I had it working fine on my Pi 4 via docker, but now when I try to re-run the command, it returns a bunch of error messages, starting with

Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nl.carosi.remarkablepocket.SyncService': Unsatisfied dependency expressed through constructor parameter 6; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.time.Duration'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@org.springframework.beans.factory.annotation.Value java.time.Duration] for value 'PT300'; nested exception is java.lang.IllegalArgumentException: 'PT300' is not a valid ISO-8601 duration

I'm at a loss as to what to try next.  I've already tried restarting the Pi and stopping and restarting the container via Portainer.  Any help is greatly appreciated!  It was working great for the first 2 syncs!

**Comment by Raiders95** [comment]
I just noticed the error only happens when I use the command here, but if I change the end of the command to "ghcr.io/nov1n/remarkable-pocket:0.2.0" instead of 0.2.1 as shown in the instructions, I get the same error as @francoissabot

**Comment by nov1n** [comment]
Can you paste the full command?

`'PT300' is not a valid ISO-8601 duration` could mean you provided an invalid duration to the `-i` flag.

**Comment by Raiders95** [comment]
**Here's what I ran:**
touch ~/.remarkable-pocket ~/.rmapi && mkdir -p ~/.rmapi-cache && docker run -it --env TZ=Pacific/Honolulu -p 65112:65112 -v ~/.remarkable-pocket:/root/.remarkable-pocket -v ~/.rmapi:/root/.rmapi -v ~/.rmapi-cache:/root/.cache/rmapi ghcr.io/nov1n/remarkable-pocket:0.2.1 -i=10

**Note that I appended the -i=10 to the end of the command because I was testing if I could make the interval to 10 minutes instead of 60.  Did I misunderstand the configuration instructions?**

**And this is the result:**
[2022-09-14 05:02:10] Refreshing cache... This may take a while.
[2022-09-14 05:02:11] WARNING!!!
[2022-09-14 05:02:11] rmapi version
[2022-09-14 05:02:11] 0.0.20
[2022-09-14 05:02:11]   Using the new 1.5 sync, this has not been fully tested yet!!!
[2022-09-14 05:02:11]   Make sure you have a backup, in case there is a bug that could cause data loss!
[2022-09-14 05:02:11] 
[2022-09-14 05:02:13] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nl.carosi.remarkablepocket.SyncService': Unsatisfied dependency expressed through constructor parameter 6; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.time.Duration'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@org.springframework.beans.factory.annotation.Value java.time.Duration] for value 'PT10'; nested exception is java.lang.IllegalArgumentException: 'PT10' is not a valid ISO-8601 duration
[2022-09-14 05:02:13] 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[2022-09-14 05:02:13] Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nl.carosi.remarkablepocket.SyncService': Unsatisfied dependency expressed through constructor parameter 6; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.time.Duration'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@org.springframework.beans.factory.annotation.Value java.time.Duration] for value 'PT10'; nested exception is java.lang.IllegalArgumentException: 'PT10' is not a valid ISO-8601 duration
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:143)
	at nl.carosi.remarkablepocket.SyncCommand.call(SyncCommand.java:125)
	at nl.carosi.remarkablepocket.SyncCommand.call(SyncCommand.java:16)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at nl.carosi.remarkablepocket.SyncCommand.main(SyncCommand.java:93)
Caused by: org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.time.Duration'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@org.springframework.beans.factory.annotation.Value java.time.Duration] for value 'PT10'; nested exception is java.lang.IllegalArgumentException: 'PT10' is not a valid ISO-8601 duration
	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:79)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1328)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 26 common frames omitted
Caused by: org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@org.springframework.beans.factory.annotation.Value java.time.Duration] for value 'PT10'; nested exception is java.lang.IllegalArgumentException: 'PT10' is not a valid ISO-8601 duration
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:192)
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:129)
	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:73)
	... 30 common frames omitted
Caused by: java.lang.IllegalArgumentException: 'PT10' is not a valid ISO-8601 duration
	at org.springframework.boot.convert.DurationStyle$2.parse(DurationStyle.java:73)
	at org.springframework.boot.convert.StringToDurationConverter.convert(StringToDurationConverter.java:64)
	at org.springframework.boot.convert.StringToDurationConverter.convert(StringToDurationConverter.java:49)
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41)
	... 33 common frames omitted
Caused by: java.time.format.DateTimeParseException: Text cannot be parsed to a Duration
	at java.base/java.time.Duration.parse(Unknown Source)
	at org.springframework.boot.convert.DurationStyle$2.parse(DurationStyle.java:70)
	... 36 common frames omitted
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nl.carosi.remarkablepocket.SyncService': Unsatisfied dependency expressed through constructor parameter 6; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.time.Duration'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@org.springframework.beans.factory.annotation.Value java.time.Duration] for value 'PT10'; nested exception is java.lang.IllegalArgumentException: 'PT10' is not a valid ISO-8601 duration
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:143)
	at nl.carosi.remarkablepocket.SyncCommand.call(SyncCommand.java:125)
	at nl.carosi.remarkablepocket.SyncCommand.call(SyncCommand.java:16)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at nl.carosi.remarkablepocket.SyncCommand.main(SyncCommand.java:93)
Caused by: org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.time.Duration'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@org.springframework.beans.factory.annotation.Value java.time.Duration] for value 'PT10'; nested exception is java.lang.IllegalArgumentException: 'PT10' is not a valid ISO-8601 duration
	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:79)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1328)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 26 more
Caused by: org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@org.springframework.beans.factory.annotation.Value java.time.Duration] for value 'PT10'; nested exception is java.lang.IllegalArgumentException: 'PT10' is not a valid ISO-8601 duration
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:192)
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:129)
	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:73)
	... 30 more
Caused by: java.lang.IllegalArgumentException: 'PT10' is not a valid ISO-8601 duration
	at org.springframework.boot.convert.DurationStyle$2.parse(DurationStyle.java:73)
	at org.springframework.boot.convert.StringToDurationConverter.convert(StringToDurationConverter.java:64)
	at org.springframework.boot.convert.StringToDurationConverter.convert(StringToDurationConverter.java:49)
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41)
	... 33 more
Caused by: java.time.format.DateTimeParseException: Text cannot be parsed to a Duration
	at java.base/java.time.Duration.parse(Unknown Source)
	at org.springframework.boot.convert.DurationStyle$2.parse(DurationStyle.java:70)
	... 36 more

**Comment by nov1n** [comment]
To change the interval please append a time unit to the value, e.g. `-i=10m` for once every 10 minutes.

**Comment by Raiders95** [comment]
**Ok, I misunderstood the configuration instructions.  It runs now, but I get the same result as @francoissabot:**
[2022-09-14 05:10:31] Refreshing cache... This may take a while.
[2022-09-14 05:10:33] WARNING!!!
[2022-09-14 05:10:33] rmapi version
[2022-09-14 05:10:33]   Using the new 1.5 sync, this has not been fully tested yet!!!
[2022-09-14 05:10:33] 0.0.20
[2022-09-14 05:10:33]   Make sure you have a backup, in case there is a bug that could cause data loss!
[2022-09-14 05:10:33] 
[2022-09-14 05:10:35] Starting sync...
[2022-09-14 05:11:06] Error occurred during sync: entry
[2022-09-14 05:11:06] Next sync in 10m.

**I didn't touch anything in my /Pocket/ folder on my RM device, and I didn't manually upload anything in that folder (although I do upload files to the RM via the my.remarkable.com site).

Here's the verbose output:**
[2022-09-14 05:15:17] Created temporary storage directory: /tmp/7918361333388812930.
[2022-09-14 05:15:18] Refreshing cache... This may take a while.
[2022-09-14 05:15:18] WARNING!!!
[2022-09-14 05:15:18] rmapi version
[2022-09-14 05:15:18] 0.0.20
[2022-09-14 05:15:18]   Using the new 1.5 sync, this has not been fully tested yet!!!
[2022-09-14 05:15:18]   Make sure you have a backup, in case there is a bug that could cause data loss!
[2022-09-14 05:15:18] 
[2022-09-14 05:15:19] Created temporary working directory: /tmp/758672993554779706.
[2022-09-14 05:15:19] Executing command: [/usr/local/bin/rmapi_arm, -ni, mkdir, Pocket]
[2022-09-14 05:15:19] entry already exists
[2022-09-14 05:15:20] Starting sync...
[2022-09-14 05:15:20] Executing command: [/usr/local/bin/rmapi_arm, -ni, ls, /Pocket/]
[2022-09-14 05:15:20] Executing command: [grep, ^\[f\]]
[2022-09-14 05:15:20] Executing command: [cut, -b5-]
[2022-09-14 05:15:21] There's a Wire Above Manhattan That You've Probably Never Noticed
[2022-09-14 05:15:21] Yubico's perspective and resource guide to passkeys 101
[2022-09-14 05:15:21] The Secret Life of a Coronavirus
[2022-09-14 05:15:21] The Cheating Scandal That Ripped the Poker World Apart
[2022-09-14 05:15:21] How to be indistractable
[2022-09-14 05:15:21] 2 Companies Say Their Vaccines Are 95% Effective. What Does That Mean?
[2022-09-14 05:15:21] Breaking Eighty Review - Is Arccos it worth it?
[2022-09-14 05:15:21] Meet the Excel warriors saving the world from spreadsheet disaster
[2022-09-14 05:15:21] Can You Catch Up on Lost Sleep?
[2022-09-14 05:15:21] In passwordless authentication, who is holding the keys?
[2022-09-14 05:15:21] This Cloud Computing Billing Expert Is Very Funny. Seriously.
[2022-09-14 05:15:21] Getting metadata for document: There's a Wire Above Manhattan That You've Probably Never Noticed.
[2022-09-14 05:15:21] Executing command: [/usr/local/bin/rmapi_arm, -ni, get, /Pocket/There's a Wire Above Manhattan That You've Probably Never Noticed]
[2022-09-14 05:15:26] downloading: [/Pocket/There's a Wire Above Manhattan That You've Probably Never Noticed]...
[2022-09-14 05:15:26] OK
[2022-09-14 05:15:26] Executing command: [mv, There's a Wire Above Manhattan That You've Probably Never Noticed.zip, /tmp/758672993554779706]
[2022-09-14 05:15:26] Executing command: [/usr/local/bin/rmapi_arm, -ni, stat, /Pocket/There's a Wire Above Manhattan That You've Probably Never Noticed]
[2022-09-14 05:15:26] Executing command: [sed, /{/,$!d]
[2022-09-14 05:15:27] {
[2022-09-14 05:15:27]   "ID": "63a34b1e-3781-4eb6-98ff-4539198c5fe2",
[2022-09-14 05:15:27]   "Version": 0,
[2022-09-14 05:15:27]   "Message": "",
[2022-09-14 05:15:27]   "Success": false,
[2022-09-14 05:15:27]   "BlobURLGet": "",
[2022-09-14 05:15:27]   "BlobURLGetExpires": "",
[2022-09-14 05:15:27]   "ModifiedClient": "52684811-04-18T14:26:08Z",
[2022-09-14 05:15:27]   "Type": "DocumentType",
[2022-09-14 05:15:27]   "VissibleName": "There's a Wire Above Manhattan That You've Probably Never Noticed",
[2022-09-14 05:15:27]   "CurrentPage": 1,
[2022-09-14 05:15:27]   "Bookmarked": false,
[2022-09-14 05:15:27]   "Parent": "bdc00fc5-4b5f-4d79-b017-d9174ac843f6"
[2022-09-14 05:15:27] }
[2022-09-14 05:15:27] There's a Wire Above Manhattan That You've Probably Never Noticed: Current page: 2, page count: 2.
[2022-09-14 05:15:27] Getting metadata for document: Yubico's perspective and resource guide to passkeys 101.
[2022-09-14 05:15:27] Executing command: [/usr/local/bin/rmapi_arm, -ni, get, /Pocket/Yubico's perspective and resource guide to passkeys 101]
[2022-09-14 05:15:33] downloading: [/Pocket/Yubico's perspective and resource guide to passkeys 101]...
[2022-09-14 05:15:33] OK
[2022-09-14 05:15:33] Executing command: [mv, Yubico's perspective and resource guide to passkeys 101.zip, /tmp/758672993554779706]
[2022-09-14 05:15:33] Executing command: [/usr/local/bin/rmapi_arm, -ni, stat, /Pocket/Yubico's perspective and resource guide to passkeys 101]
[2022-09-14 05:15:33] Executing command: [sed, /{/,$!d]
[2022-09-14 05:15:34] {
[2022-09-14 05:15:34]   "ID": "7f34e04e-ed2f-4cf0-882e-8a1d91ccc803",
[2022-09-14 05:15:34]   "Version": 0,
[2022-09-14 05:15:34]   "Message": "",
[2022-09-14 05:15:34]   "Success": false,
[2022-09-14 05:15:34]   "BlobURLGet": "",
[2022-09-14 05:15:34]   "BlobURLGetExpires": "",
[2022-09-14 05:15:34]   "ModifiedClient": "52689921-08-06T13:17:42Z",
[2022-09-14 05:15:34]   "Type": "DocumentType",
[2022-09-14 05:15:34]   "VissibleName": "Yubico's perspective and resource guide to passkeys 101",
[2022-09-14 05:15:34]   "CurrentPage": 0,
[2022-09-14 05:15:34]   "Bookmarked": false,
[2022-09-14 05:15:34]   "Parent": "bdc00fc5-4b5f-4d79-b017-d9174ac843f6"
[2022-09-14 05:15:34] }
[2022-09-14 05:15:34] Yubico's perspective and resource guide to passkeys 101: Current page: 1, page count: 3.
[2022-09-14 05:15:34] Getting metadata for document: The Secret Life of a Coronavirus.
[2022-09-14 05:15:34] Executing command: [/usr/local/bin/rmapi_arm, -ni, get, /Pocket/The Secret Life of a Coronavirus]
[2022-09-14 05:15:40] downloading: [/Pocket/The Secret Life of a Coronavirus]...
[2022-09-14 05:15:40] OK
[2022-09-14 05:15:40] Executing command: [mv, The Secret Life of a Coronavirus.zip, /tmp/758672993554779706]
[2022-09-14 05:15:40] Executing command: [/usr/local/bin/rmapi_arm, -ni, stat, /Pocket/The Secret Life of a Coronavirus]
[2022-09-14 05:15:40] Executing command: [sed, /{/,$!d]
[2022-09-14 05:15:41] {
[2022-09-14 05:15:41]   "ID": "3a2fe45d-f25e-4ea8-9242-7777aa63836e",
[2022-09-14 05:15:41]   "Version": 0,
[2022-09-14 05:15:41]   "Message": "",
[2022-09-14 05:15:41]   "Success": false,
[2022-09-14 05:15:41]   "BlobURLGet": "",
[2022-09-14 05:15:41]   "BlobURLGetExpires": "",
[2022-09-14 05:15:41]   "ModifiedClient": "52681266-02-09T10:07:37Z",
[2022-09-14 05:15:41]   "Type": "DocumentType",
[2022-09-14 05:15:41]   "VissibleName": "The Secret Life of a Coronavirus",
[2022-09-14 05:15:41]   "CurrentPage": 0,
[2022-09-14 05:15:41]   "Bookmarked": false,
[2022-09-14 05:15:41]   "Parent": "bdc00fc5-4b5f-4d79-b017-d9174ac843f6"
[2022-09-14 05:15:41] }
[2022-09-14 05:15:41] The Secret Life of a Coronavirus: Current page: 1, page count: 2.
[2022-09-14 05:15:41] Getting metadata for document: The Cheating Scandal That Ripped the Poker World Apart.
[2022-09-14 05:15:41] Executing command: [/usr/local/bin/rmapi_arm, -ni, get, /Pocket/The Cheating Scandal That Ripped the Poker World Apart]
[2022-09-14 05:15:44] downloading: [/Pocket/The Cheating Scandal That Ripped the Poker World Apart]...
[2022-09-14 05:15:44] OK
[2022-09-14 05:15:44] Executing command: [mv, The Cheating Scandal That Ripped the Poker World Apart.zip, /tmp/758672993554779706]
[2022-09-14 05:15:44] Error occurred during sync: entry
[2022-09-14 05:15:44] Stack trace:
java.lang.NullPointerException: entry
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at java.base/java.util.zip.ZipFile.getInputStream(Unknown Source)
	at nl.carosi.remarkablepocket.MetadataProvider.getMetadata(MetadataProvider.java:71)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
	at nl.carosi.remarkablepocket.RemarkableService.listReadDocuments(RemarkableService.java:49)
	at nl.carosi.remarkablepocket.SyncService.archiveReadArticles(SyncService.java:108)
	at nl.carosi.remarkablepocket.SyncService.syncImpl(SyncService.java:83)
	at nl.carosi.remarkablepocket.SyncService.sync(SyncService.java:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[2022-09-14 05:15:44] Next sync in 10m.

**Comment by nov1n** [comment]
Can you try to delete all articles in the Pocket directory manually, and then run v0.2.1? If that still doesn't work I'll have to look into this further, though I have not yet managed to reproduce this issue.

**Comment by Raiders95** [comment]
OK, I deleted the files on the RM device and emptied the trash. It seems like it's working again.   Thanks! I might have annotated one of the articles on the RM.  Not sure if that's the reason for the error.

Also, I'm running this on my Raspberry Pi through a terminal window via VNC.   Since this is just a command line program, am I correct in assuming I just close the VNC connection and leave the terminal window and command running at the "Next sync in" message?  I cannot "quit" the command via Ctrl C, because then it won't sync, correct?

Thanks again for all your help.  I love that this exists.  I sent a few coffees your way.

**Comment by Raiders95** [comment]
Hmm, I might have spoke too soon.  I canceled and re-ran the command because I wanted to make the sync interval at 8 hours, and now I have 18 articles on my RM?  

It still ran fine, but a couple of the articles that it put on this time were already 100% read.

I'll continue to monitor and report back if there's anything further.  Thanks

**Comment by nov1n** [comment]
> OK, I deleted the files on the RM device and emptied the trash. It seems like it's working again. Thanks! I might have annotated one of the articles on the RM. Not sure if that's the reason for the error.

This should not be a problem.

> Also, I'm running this on my Raspberry Pi through a terminal window via VNC. Since this is just a command line program, am I correct in assuming I just close the VNC connection and leave the terminal window and command running at the "Next sync in" message? I cannot "quit" the command via Ctrl C, because then it won't sync, correct?

If you press Ctrl C the command will indeed stop. To keep it running you have a few options:

- Use Ctrl Z to send the process to the background.
- Use the docker command without the `-it` flags.
- Keep the terminal open and quit VNC.
- Use docker-compose as `docker-compose up -d` in conjunction with the docker-compose file [here](https://github.com/nov1n/RemarkablePocket/blob/main/docker-compose.yml). This is the solution I use on my Raspberry Pi and it ensures that the process always keeps running.

> Thanks again for all your help. I love that this exists. I sent a few coffees your way.

Thanks, that means a lot. :-)

> Hmm, I might have spoke too soon. I canceled and re-ran the command because I wanted to make the sync interval at 8 hours, and now I have 18 articles on my RM?

This is very strange behavior and I have no explanation for it. The only thing I can think of is that you ran the command with `-l=18` which increases the article limit.

> It still ran fine, but a couple of the articles that it put on this time were already 100% read.

> I'll continue to monitor and report back if there's anything further. Thanks

I'm not sure how to explain this either. Please keep an eye on it and let me know if it happens again in which case we'll need to do some more digging.

**Comment by Raiders95** [comment]
Update - The command got stuck again with repeating errors:
[2022-09-15 21:43:04] Starting sync...
[2022-09-15 21:43:30] Error occurred during sync: entry
[2022-09-15 21:43:30] Next sync in 8h.

I canceled and re-ran with -v and one of my articles seemed to be causing the error, so I deleted it from the RM, let the RM sync, and then re-ran, with the same result.  I then deleted the article from my RM, let the RM sync, then deleted the same article from my Pocket list, re-ran the command, and it got stuck again on a different article.  

I thought perhaps it's related that I had more articles in my RM than I'm supposed to (I had 18 articles on the RM), so I deleted everything out of the pocket folder on my RM, let the RM sync, and re-ran the command.  It ran fine, and I now have only 10 articles on my RM.  However two of the articles I have on my RM were already 100% read prior to the error message, but now show (in RM and Pocket) as unread.  Not a big deal, but strange behavior, nonetheless.

Hopefully I've excised all the bugs in my article list.

Regarding docker-compose, if I already have that file on my Pi (from other docker containers), is it best to append the commands you linked to the end of my existing docker-compose.yml file and re-run?  If I go with this route, I won't be able to see the output/status though?

Thanks for all the help.

**Comment by nov1n** [comment]
>Update - The command got stuck again with repeating errors:
[2022-09-15 21:43:04] Starting sync...
[2022-09-15 21:43:30] Error occurred during sync: entry
[2022-09-15 21:43:30] Next sync in 8h.

I managed to reproduce this bug today. Some articles are saved to the Remarkable as PDFs instead of epubs which causes the program to fail. I am working on a fix.

> Regarding docker-compose, if I already have that file on my Pi (from other docker containers), is it best to append the commands you linked to the end of my existing docker-compose.yml file and re-run? If I go with this route, I won't be able to see the output/status though? Same with the Ctrl-Z route? Sorry, I'm new with Pi and Linux commands. I just know enough to get myself in trouble. 

You can use separate docker-compose files. Additional flags such as `-i=10` can be added to the 'command' section like this:
```
...
services:
  remarkable-pocket:
    image: ghcr.io/nov1n/remarkable-pocket:0.2.1
    command: -i=10
...
```

**Comment by Raiders95** [comment]
Thanks again for helping troubleshoot.  I'm glad that you were able to reproduce the error and that it's not from my user error, but bummer that it's not working properly.  Hopefully you can find a fix.

Thanks for the docker compose help.  I'll probably just leave it as is for now until I get motivated to try and tinker with it again.

**Comment by nov1n** [comment]
Sounds good! Will close this issue and post updates in #11.
