### ISSUE TITLE
UnsatisfiedDependencyException: Cannot run program "/usr/local/bin/rmapi": error=2, No such file or directory

### ISSUE THREAD

**Issue by andypillip** [nov1n/RemarkablePocket#16]
Hi there.

After the issue with the new API version I found some time to give RemarkablePocket another spin. Unfortunately, the software crashes with a ton of exceptions, apparently one caused by the other.

It would be great to get some help on this. Thanks very much!

I removed the three files and ran the command described in the Readme:

    $ touch ~/.remarkable-pocket ~/.rmapi && mkdir -p ~/.rmapi-cache && docker run -it --env TZ=Europe/Amsterdam -p 65112:65112 -v ~/.remarkable-pocket:/root/.remarkable-pocket:Z -v ~/.rmapi:/root/.rmapi:Z -v ~/.rmapi-cache:/root/.cache/rmapi:Z ghcr.io/nov1n/remarkable-pocket:0.2.2

I only added `:Z` to the volume mappings which is necessary to work with SELinux and also tried version 0.2.2 which seems to be released but not mentioned in the Readme.

The first line output is the following:

> [2022-10-08 15:32:08] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nl.carosi.remarkablepocket.ArticleValidator': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nl.carosi.remarkablepocket.MetadataProvider': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nl.carosi.remarkablepocket.RemarkableApi': Invocation of init method failed; nested exception is java.lang.RuntimeException: Could not authenticate to Remarkable API

I believe this is an accumulation of all other exceptions output in red in the log. The second one being:

> Caused by: java.io.IOException: Cannot run program "/usr/local/bin/rmapi": error=2, No such file or directory

**Comment by nov1n** [comment]
Hi, Remarkable Cloud changed their API again, and I'm waiting for `rmapi` to write a fix for then client. See also https://github.com/nov1n/RemarkablePocket/issues/11.

That said, I'm not sure your error is related. Can you change the version to `0.2.3`, append `-v` to the command for verbose logging, and post the output?

**Comment by andypillip** [comment]
Thanks for the quick response. No I guess there simply is some reference messed up.

They changed again? Sadly they do not officially support their API. /:

> $ touch ~/.remarkable-pocket ~/.rmapi && mkdir -p ~/.rmapi-cache && docker run -it --env TZ=Europe/Amsterdam -p 65112:65112 -v ~/.remarkable-pocket:/root/.remarkable-pocket:Z -v ~/.rmapi:/root/.rmapi:Z -v ~/.rmapi-cache:/root/.cache/rmapi:Z ghcr.io/nov1n/remarkable-pocket:0.2.3 -v


```
[2022-10-08 15:55:18] Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nl.carosi.remarkablepocket.MetadataProvider': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nl.carosi.remarkablepocket.RemarkableApi': Invocation of init method failed; nested exception is java.lang.RuntimeException: Could not authenticate to Remarkable API
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:143)
	at nl.carosi.remarkablepocket.SyncCommand.call(SyncCommand.java:125)
	at nl.carosi.remarkablepocket.SyncCommand.call(SyncCommand.java:16)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at nl.carosi.remarkablepocket.SyncCommand.main(SyncCommand.java:93)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nl.carosi.remarkablepocket.RemarkableApi': Invocation of init method failed; nested exception is java.lang.RuntimeException: Could not authenticate to Remarkable API
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 26 common frames omitted
Caused by: java.lang.RuntimeException: Could not authenticate to Remarkable API
	at nl.carosi.remarkablepocket.RemarkableApi.login(RemarkableApi.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 39 common frames omitted
Caused by: java.io.IOException: Cannot run program "/usr/local/bin/rmapi": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at nl.carosi.remarkablepocket.RemarkableApi.login(RemarkableApi.java:103)
	... 46 common frames omitted
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 49 common frames omitted
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nl.carosi.remarkablepocket.MetadataProvider': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nl.carosi.remarkablepocket.RemarkableApi': Invocation of init method failed; nested exception is java.lang.RuntimeException: Could not authenticate to Remarkable API
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:143)
	at nl.carosi.remarkablepocket.SyncCommand.call(SyncCommand.java:125)
	at nl.carosi.remarkablepocket.SyncCommand.call(SyncCommand.java:16)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at nl.carosi.remarkablepocket.SyncCommand.main(SyncCommand.java:93)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nl.carosi.remarkablepocket.RemarkableApi': Invocation of init method failed; nested exception is java.lang.RuntimeException: Could not authenticate to Remarkable API
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 26 more
Caused by: java.lang.RuntimeException: Could not authenticate to Remarkable API
	at nl.carosi.remarkablepocket.RemarkableApi.login(RemarkableApi.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 39 more
Caused by: java.io.IOException: Cannot run program "/usr/local/bin/rmapi": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at nl.carosi.remarkablepocket.RemarkableApi.login(RemarkableApi.java:103)
	... 46 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 49 more
```

**Comment by nov1n** [comment]
No, sadly not... So we're always one step behind :/

So the `rmapi` binary should actually be named `rmapi_amd64` when running in Docker, see https://github.com/nov1n/RemarkablePocket/blob/main/src/main/java/nl/carosi/remarkablepocket/RemarkableApi.java#L37.

Can you post the output of `docker -v` and `docker run eclipse-temurin:17-jre ls /.dockerenv`?

**Comment by andypillip** [comment]
I’m on Fedora which comes with podman instead of Docker. I aliased it to `docker`.

> podman version 4.2.1

    $ docker run eclipse-temurin:17-jre ls /.dockerenv
    ls: cannot access '/.dockerenv': No such file or directory

But I’m a bit lost as to how that is related with the wrong binary name.

**Comment by nov1n** [comment]
In the code I check for the existence of this file which is a common way to detect whether the process is running inside a container. If it exists one of 3 binaries based on the CPU architecture (amd64, arm, arm64) is selected. If the file does not exist it falls back `/usr/local/bin/rmapi` which I use for testing the program outside of Docker.

I also assumed Docker and Podman were compatible, but apparently, they differ in this regard. I'll push a fix tomorrow.

**Comment by andypillip** [comment]
I just installed Docker to test, but it seems it’s reusing the containers. I’ll try cleaning up…

**Comment by andypillip** [comment]
Alright, with Docker it seems to work. It would be amazing if you added support for Podman, but I understand if you don’t. I’m happy to close this ticket then.

I do get some 500 errors, but I guess they are related to the API changes:

> [2022-10-08 18:24:17] Executing command: [/usr/local/bin/rmapi_amd64, -ni, rm, /Pocket/How To Run a Consequence Scanning Workshop]
> [2022-10-08 18:24:18] ERROR: 2022/10/08 18:24:18 apictx.go:431: cannot send sync request failed with status 500
> [2022-10-08 18:24:18] entry(s) deleted

On the other hand, that error is not caught, there’s still a confirmation in the output: entry(s) deleted

**Comment by nov1n** [comment]
Can run `docker pull ghcr.io/nov1n/remarkable-pocket:0.2.3` and then try to run the command again with Podman?

**Comment by andypillip** [comment]
Docker pulled the latest image, and then I used the command with `podman` instead of `docker`.
Unfortunately it gave the same error.

I then deleted the image, and ran the command again, this time I additionally got these messages:

> [2022-10-09 12:33:15] Created temporary storage directory: /tmp/739640235270387859.
> [2022-10-09 12:33:15] Created temporary working directory: /tmp/8561779150430268827.
> [2022-10-09 12:33:15] open /root/.cache/rmapi/.tree
> [2022-10-09 12:33:15] permission deniedopen /root/.cache/rmapi/.tree
> [2022-10-09 12:33:16] permission deniedopen /root/.cache/rmapi/.tree
> [2022-10-09 12:33:16] ERROR
> [2022-10-09 12:33:16] 2022/10/09 12:33:16 main.go:50
> [2022-10-09 12:33:16] failed to build documents tree, last error
> [2022-10-09 12:33:16] open /root/.cache/rmapi/.tree
> [2022-10-09 12:33:16] permission denied
> [2022-10-09 12:33:16] permission denied

**Comment by nov1n** [comment]
I just tried with Podman and it works for me. Could this be related to SELinux?
